# Generated by Django 2.2 on 2021-11-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='colour',
            options={'verbose_name_plural': 'colours'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name_plural': 'Sellers'},
        ),
    ]
